package com.project.jaijite.greendao.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.project.jaijite.entity.LightInfo;
import com.project.jaijite.entity.DeviceInfo;

import com.project.jaijite.greendao.dao.LightInfoDao;
import com.project.jaijite.greendao.dao.DeviceInfoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig lightInfoDaoConfig;
    private final DaoConfig deviceInfoDaoConfig;

    private final LightInfoDao lightInfoDao;
    private final DeviceInfoDao deviceInfoDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        lightInfoDaoConfig = daoConfigMap.get(LightInfoDao.class).clone();
        lightInfoDaoConfig.initIdentityScope(type);

        deviceInfoDaoConfig = daoConfigMap.get(DeviceInfoDao.class).clone();
        deviceInfoDaoConfig.initIdentityScope(type);

        lightInfoDao = new LightInfoDao(lightInfoDaoConfig, this);
        deviceInfoDao = new DeviceInfoDao(deviceInfoDaoConfig, this);

        registerDao(LightInfo.class, lightInfoDao);
        registerDao(DeviceInfo.class, deviceInfoDao);
    }
    
    public void clear() {
        lightInfoDaoConfig.clearIdentityScope();
        deviceInfoDaoConfig.clearIdentityScope();
    }

    public LightInfoDao getLightInfoDao() {
        return lightInfoDao;
    }

    public DeviceInfoDao getDeviceInfoDao() {
        return deviceInfoDao;
    }

}
