package com.project.jaijite.greendao.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.project.jaijite.entity.LightInfo;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "LIGHT_INFO".
*/
public class LightInfoDao extends AbstractDao<LightInfo, Long> {

    public static final String TABLENAME = "LIGHT_INFO";

    /**
     * Properties of entity LightInfo.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Name = new Property(1, String.class, "name", false, "NAME");
        public final static Property Light_level = new Property(2, int.class, "light_level", false, "LIGHT_LEVEL");
        public final static Property Color_temp = new Property(3, int.class, "color_temp", false, "COLOR_TEMP");
        public final static Property Time_on = new Property(4, String.class, "time_on", false, "TIME_ON");
        public final static Property Time_off = new Property(5, String.class, "time_off", false, "TIME_OFF");
        public final static Property Delay = new Property(6, String.class, "delay", false, "DELAY");
        public final static Property Jump = new Property(7, int.class, "jump", false, "JUMP");
        public final static Property Water = new Property(8, int.class, "water", false, "WATER");
        public final static Property Touch = new Property(9, int.class, "touch", false, "TOUCH");
        public final static Property Gflash = new Property(10, int.class, "gflash", false, "GFLASH");
        public final static Property Bflash = new Property(11, int.class, "bflash", false, "BFLASH");
        public final static Property Warming = new Property(12, int.class, "warming", false, "WARMING");
        public final static Property Led_state = new Property(13, int.class, "led_state", false, "LED_STATE");
        public final static Property Night_lamp_state = new Property(14, int.class, "night_lamp_state", false, "NIGHT_LAMP_STATE");
        public final static Property IsDelete = new Property(15, int.class, "isDelete", false, "IS_DELETE");
        public final static Property IsCheck = new Property(16, Boolean.class, "isCheck", false, "IS_CHECK");
    }


    public LightInfoDao(DaoConfig config) {
        super(config);
    }
    
    public LightInfoDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"LIGHT_INFO\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"NAME\" TEXT," + // 1: name
                "\"LIGHT_LEVEL\" INTEGER NOT NULL ," + // 2: light_level
                "\"COLOR_TEMP\" INTEGER NOT NULL ," + // 3: color_temp
                "\"TIME_ON\" TEXT," + // 4: time_on
                "\"TIME_OFF\" TEXT," + // 5: time_off
                "\"DELAY\" TEXT," + // 6: delay
                "\"JUMP\" INTEGER NOT NULL ," + // 7: jump
                "\"WATER\" INTEGER NOT NULL ," + // 8: water
                "\"TOUCH\" INTEGER NOT NULL ," + // 9: touch
                "\"GFLASH\" INTEGER NOT NULL ," + // 10: gflash
                "\"BFLASH\" INTEGER NOT NULL ," + // 11: bflash
                "\"WARMING\" INTEGER NOT NULL ," + // 12: warming
                "\"LED_STATE\" INTEGER NOT NULL ," + // 13: led_state
                "\"NIGHT_LAMP_STATE\" INTEGER NOT NULL ," + // 14: night_lamp_state
                "\"IS_DELETE\" INTEGER NOT NULL ," + // 15: isDelete
                "\"IS_CHECK\" INTEGER);"); // 16: isCheck
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"LIGHT_INFO\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, LightInfo entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(2, name);
        }
        stmt.bindLong(3, entity.getLight_level());
        stmt.bindLong(4, entity.getColor_temp());
 
        String time_on = entity.getTime_on();
        if (time_on != null) {
            stmt.bindString(5, time_on);
        }
 
        String time_off = entity.getTime_off();
        if (time_off != null) {
            stmt.bindString(6, time_off);
        }
 
        String delay = entity.getDelay();
        if (delay != null) {
            stmt.bindString(7, delay);
        }
        stmt.bindLong(8, entity.getJump());
        stmt.bindLong(9, entity.getWater());
        stmt.bindLong(10, entity.getTouch());
        stmt.bindLong(11, entity.getGflash());
        stmt.bindLong(12, entity.getBflash());
        stmt.bindLong(13, entity.getWarming());
        stmt.bindLong(14, entity.getLed_state());
        stmt.bindLong(15, entity.getNight_lamp_state());
        stmt.bindLong(16, entity.getIsDelete());
 
        Boolean isCheck = entity.getIsCheck();
        if (isCheck != null) {
            stmt.bindLong(17, isCheck ? 1L: 0L);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, LightInfo entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(2, name);
        }
        stmt.bindLong(3, entity.getLight_level());
        stmt.bindLong(4, entity.getColor_temp());
 
        String time_on = entity.getTime_on();
        if (time_on != null) {
            stmt.bindString(5, time_on);
        }
 
        String time_off = entity.getTime_off();
        if (time_off != null) {
            stmt.bindString(6, time_off);
        }
 
        String delay = entity.getDelay();
        if (delay != null) {
            stmt.bindString(7, delay);
        }
        stmt.bindLong(8, entity.getJump());
        stmt.bindLong(9, entity.getWater());
        stmt.bindLong(10, entity.getTouch());
        stmt.bindLong(11, entity.getGflash());
        stmt.bindLong(12, entity.getBflash());
        stmt.bindLong(13, entity.getWarming());
        stmt.bindLong(14, entity.getLed_state());
        stmt.bindLong(15, entity.getNight_lamp_state());
        stmt.bindLong(16, entity.getIsDelete());
 
        Boolean isCheck = entity.getIsCheck();
        if (isCheck != null) {
            stmt.bindLong(17, isCheck ? 1L: 0L);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public LightInfo readEntity(Cursor cursor, int offset) {
        LightInfo entity = new LightInfo( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // name
            cursor.getInt(offset + 2), // light_level
            cursor.getInt(offset + 3), // color_temp
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // time_on
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // time_off
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // delay
            cursor.getInt(offset + 7), // jump
            cursor.getInt(offset + 8), // water
            cursor.getInt(offset + 9), // touch
            cursor.getInt(offset + 10), // gflash
            cursor.getInt(offset + 11), // bflash
            cursor.getInt(offset + 12), // warming
            cursor.getInt(offset + 13), // led_state
            cursor.getInt(offset + 14), // night_lamp_state
            cursor.getInt(offset + 15), // isDelete
            cursor.isNull(offset + 16) ? null : cursor.getShort(offset + 16) != 0 // isCheck
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, LightInfo entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setName(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setLight_level(cursor.getInt(offset + 2));
        entity.setColor_temp(cursor.getInt(offset + 3));
        entity.setTime_on(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setTime_off(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setDelay(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setJump(cursor.getInt(offset + 7));
        entity.setWater(cursor.getInt(offset + 8));
        entity.setTouch(cursor.getInt(offset + 9));
        entity.setGflash(cursor.getInt(offset + 10));
        entity.setBflash(cursor.getInt(offset + 11));
        entity.setWarming(cursor.getInt(offset + 12));
        entity.setLed_state(cursor.getInt(offset + 13));
        entity.setNight_lamp_state(cursor.getInt(offset + 14));
        entity.setIsDelete(cursor.getInt(offset + 15));
        entity.setIsCheck(cursor.isNull(offset + 16) ? null : cursor.getShort(offset + 16) != 0);
     }
    
    @Override
    protected final Long updateKeyAfterInsert(LightInfo entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(LightInfo entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(LightInfo entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
